name: Build Package
on:
  push:
    branches:
      - main
jobs:
  build-main-ui-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - run: cd homepage-main-ui

      - uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Log in to the Github registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}   

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/${{ github.repository }}/main-ui    

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./homepage-main-ui
          file: ./homepage-main-ui/Dockerfile
          push: true
          tags: ghcr.io/matt-mano/${{ github.repository }}/main-ui/latest
          labels: ${{ steps.meta.outputs.labels }}

  build-cms-api-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - run: cd homepage-cms-api

      - name: Log in to the Github registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}   

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/${{ github.repository }}/cms-api    

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./homepage-cms-api
          file: ./homepage-cms-api/Dockerfile
          push: true
          tags: ghcr.io/matt-mano/${{ github.repository }}/cms-api/latest
          labels: ${{ steps.meta.outputs.labels }}
  
  deploy-sites:
    needs: [build-main-ui-image, build-cms-api-image]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy sites
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ghcr.io/matt-mano/matt-mano/next-homepage/cms-api/latest:latest
            docker stop homepageapi
            docker rm homepageapi
            docker run -d -p 8087:80 --name homepageapi --env HOMEPAGE_MONGODB_URL=${{ secrets.DB_CONNECTION_STRING }} --restart unless-stopped ghcr.io/matt-mano/matt-mano/next-homepage/cms-api/latest:latest
            
            docker pull ghcr.io/matt-mano/matt-mano/next-homepage/main-ui/latest:latest
            docker stop homepage
            docker rm homepage
            docker run -d -p 8084:80 --name homepage --restart unless-stopped ghcr.io/matt-mano/matt-mano/next-homepage/main-ui/latest:latest
            
    
