name: Build Package
on:
  push:
    branches:
      - main
jobs:
  build-ui-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build container image
        uses: docker/build-push-action@v1
        with:
          repository: matt-mano/next-homepage
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
          registry: ghcr.io
          tag_with_sha: true
          tags: latest
