name: Build Package
on:
  push:
    branches:
      - dynamic-homepage
jobs:
  build-main-ui-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - run: cd homepage-main-ui

      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Github registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}   

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/${{ github.repository }}       

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: user/app:latest
          labels: ${{ steps.meta.outputs.labels }}

  build-cms-api-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: cd homepage-cms-api
